### ISSUE TITLE
Alt-selector in Linux moves windows

### ISSUE THREAD

**Issue by romansCode** [bigfive/atom-sublime-select#26]
It would be great if the Keybinding could be user changeable, as Alt with left mouse click in Gnome moves windows and block selection is not possible.

**Comment by tesfabpel** [comment]
+1 for shift+right as it is in SublimeText...  
Anyway, I've configured my DEs to move windows with the Win/Super key, so +1 to the configurable keybindings... :)

**Comment by varemenos** [comment]
Be careful with the middle click in some Linux window managers, it performs copy/pasting

**Comment by nolman** [comment]
It would be awesome to have a keybind for this so one wouldn't have to touch the mouse

**Comment by kankaristo** [comment]
On Ubuntu (Gnome, but probably Unity too) a lot of these cause problems:
- `alt+click` moves the window
- `alt+shift+click` moves the window and "grabs" the edges of the screen and other windows
- `alt+middle-click` resizes the window
- `alt+right-click` opens the window's context menu
- Any other modifier with right-click opens Atom's context menu (apparently never reaches the package)

Like @varemenos said, middle-click pastes text, so that could cause problems too.

The only thing that seems to working well in Ubuntu is `ctrl+click`.

At the risk of starting a flame war, I would *guess* that most of Atom's Linux users use Ubuntu. Because of this, the default should probably be `ctrl-click`, but configuration seems super simple to add.

**Comment by tberne** [comment]
Can I suggest it to be mouse-independent?
In Eclipse there's a column mode (Alt + Shift + A). In this mode, if expand selection down using shift + down it creates the column selection.
Besides avoid mouse-related conflicts, it is so fast.

**Comment by bigfive** [comment]
Keys are now configurable

**Comment by richarddewit** [comment]
Maybe a keeping a changelog is a good idea, I kept wondering why I couldn't do column selecting after updating. Had to search through the issues..
