### ISSUE TITLE
Doesn't work on Windows 7 or CentOS 7

### ISSUE THREAD

**Issue by noscgag** [bigfive/atom-sublime-select#64]
This is on Atom 1.0 with sublime-select 1.3.0.

I have the same version installed on OS X, Windows 7, and CentOS 7, with three different behaviors.

On OS X it seems to work just fine.

On CentOS 7 it doesn't work at all. Holding down the Alt key and dragging is the same as though Alt wasn't held down, i.e. it does a normal selection. Middle clicking is also the same -- no column select.

On Windows 7 it does do a column select (either with the Alt key held down or using the middle mouse button), but the selection is offset down and to the right by 6 columns and 2 lines.

**Comment by matteoipri** [comment]
Maybe the answer to the CentOS 7 issue is in the source code. I was curious of how this plugin was written and I found this in the first lines (from 3 to 23):

```coffeescript
inputCfg = switch os.platform()
  when 'win32'
    selectKey: 'altKey'
    mainMouseNum: 1
    middleMouseNum: 2
    enableMiddleMouse: true
  when 'darwin'
    selectKey: 'altKey'
    mainMouseNum: 1
    middleMouseNum: 2
    enableMiddleMouse: true
  when 'linux'
    selectKey: 'shiftKey'
    mainMouseNum: 2
    middleMouseNum: 2
    enableMiddleMouse: false
  else
    selectKey: 'shiftKey'
    mainMouseNum: 2
    middleMouseNum: 2
    enableMiddleMouse: false
```

I don't know exactly how this works and why the author set different values for linux, but you can try to change those lines on your CentOS installation and give it a try.
Just my idea, since I'm using Atom just on OS X right now.

**Comment by charleswhchan** [comment]
See: Issue #26 for Linux keyboard/mouse combinations.

**Comment by bigfive** [comment]
Keys are now configurable
